### PR TITLE
unwarn members some warn

### PR DESCRIPTION
**Pull request by onekin1225**
Like warn member already than unwarns the array object

### CODE REVIEW

**Comment by Androz2091** [comment]
What do you mean? Are you suggesting something?

**Comment by onekin1225** [comment]
Like someone got warn or tag wrong guys than he have too much warning , than the admin / mod wanna remove wrong warns 
(sry my grammer is too bad hope u can read it)

**Comment by Androz2091** [comment]
They can use `+clear-warns`

**Comment by onekin1225** [comment]
didnt hv that commands

**Comment by Androz2091** [comment]
My bad, `*clear-sanctions`: https://www.github.com/Androz2091/AtlantaBot/tree/master/commands%2FModeration%2Fclear-sanctions.js

**Pull request closed without merging**
