### PR TITLE
Update General, Fun, images and owner commands to DJS V13

### PR DESCRIPTION
**Pull request by bycop**
Update General/FUN/images/Owner commands with DJS V13 (Embeds, bans, ...)
Remove collection.array()
Add Guild_presences intents
Update packages versions

(Update to V13 in progress, some commands will not work until the update is finished)

### CODE REVIEW

**Comment by wesleigh** [comment]
Thanks for the PR @bycop - will have a view tonight and confer with Androz

**Comment by bycop** [comment]
I'll continue to update all commands to V13 (And slash commands but will take more time)

**Review by wesleigh — COMMENTED** [review]
Reviewed changes. Seem good to me.

Thank you for this!

**Comment by wesleigh** [comment]
@bycop - I got slightly over-excited at the sight of seeing "DJS v13", that I failed to read:
> "(Update to V13 in progress, some commands will not work until the update is finished)

Could you submit a new Pull Request to the newly created `4.12.1-alpha` [branch](https://github.com/Androz2091/AtlantaBot/tree/4.12.1-alpha)? Once we've upgraded it all to D.js 13 and tested, we can merge from `4.12.1-alpha` to `master`.

**Pull request merged**
